import {
  KINETIC_HALL_PROP_IDS,
  type KineticHallPropAsset,
  type KineticHallPropId,
  type MintPropPackDefinition,
} from './types';
import { mintRuntimeUrl } from '../mintRuntimeUrls';

export const KINETIC_HALL_PROP_PACK = Object.freeze({
  assetPackId: 'th7ae8en9v2snpkn6f3511c4f18bd2yn',
  name: 'PROJECT FORGE-5 — Kinetic Hall Dynamic Props',
  status: 'succeeded' as const,
  assetStage: 'final' as const,
  itemCount: 8,
  succeededItemCount: 8,
  failedItemCount: 0,
});

const evidencePath = 'data/mint/finals/kinetic-hall/props/artifact-manifest.json' as const;

export const KINETIC_HALL_PROP_INVENTORY = Object.freeze([
  {
    index: 0,
    id: 'powered-sliding-obstacle-sled',
    label: 'Powered Sliding Obstacle Sled',
    itemRecordId: 'td7b8h4sb0cy8e2anq3ngmn7gh8bdp6s',
    modelId: 'ks7cs8097p0qmqq20g4799sc318bcjma',
    finalAssetId: 'p978s2d61bf3bwayrrg15e32c58bd84b',
    artifactId:
      'asset_pack_item_glb:vd795smjezmkwzn67axep8qm7s8bcbkz:0:ks7cs8097p0qmqq20g4799sc318bcjma',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/00-powered-sliding-obstacle-sled'),
    filePath: 'public/models/props/kinetic-hall/00-powered-sliding-obstacle-sled.glb',
    evidencePath,
    byteSize: 922280,
    sha256: '3544aa69cc197379fc1b43de55d9ed7dbc9ba12ca13fc5f886742bff3502b207',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The whole sled is valid as a movable rigid obstacle; its one-mesh final has no separately authored internal sliding mechanism.',
    },
  },
  {
    index: 1,
    id: 'modular-weighted-safety-barrier',
    label: 'Modular Weighted Safety Barrier',
    itemRecordId: 'td7d6k2byw3mv8aj65zthbza1d8bdjwq',
    modelId: 'ks7ad5qyjngsa5yk96esxkevjd8bcr7g',
    finalAssetId: 'p97bgqt7gr1x2v5hqjfx5tv6th8bcb99',
    artifactId:
      'asset_pack_item_glb:vd795smjezmkwzn67axep8qm7s8bcbkz:1:ks7ad5qyjngsa5yk96esxkevjd8bcr7g',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/01-modular-weighted-safety-barrier'),
    filePath: 'public/models/props/kinetic-hall/01-modular-weighted-safety-barrier.glb',
    evidencePath,
    byteSize: 857668,
    sha256: '3e9a42681261f75ac6deaddae0e58ad366506f688e74b12fb7815f25243dc26c',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The one-mesh weighted barrier is valid as a movable rigid safety prop; no articulated mechanism is required.',
    },
  },
  {
    index: 2,
    id: 'instrumented-slalom-cone',
    label: 'Instrumented Slalom Cone',
    itemRecordId: 'td7drzk4qf8cjst26wemwypva98bcat9',
    modelId: 'ks74wrba2192j77rr8av33bg4x8bcnqn',
    finalAssetId: 'p971b0s0hmg7xdgh2zaa2tm2a58bcyf4',
    artifactId: 'original_glb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/02-instrumented-slalom-cone'),
    filePath: 'public/models/props/kinetic-hall/02-instrumented-slalom-cone.glb',
    evidencePath,
    byteSize: 1017232,
    sha256: '4bdd4a50541895a3ce89ce816abe57ec2faab99dd5601f365bcfcb745388a144',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The one-mesh cone is valid as a movable rigid marker with authored visual instrumentation; no articulated part is required.',
    },
  },
  {
    index: 3,
    id: 'adjustable-low-clearance-gantry',
    label: 'Adjustable Low-Clearance Gantry Insert',
    itemRecordId: 'td70n54gywkyz5g9tk7xzkszw98bcww7',
    modelId: 'ks74y946hknqdd5j82bpjwagz18bcdvg',
    finalAssetId: 'p9732es48z5c8q4dvnvd7pgk8n8bdb02',
    artifactId: 'original_glb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/03-adjustable-low-clearance-gantry'),
    filePath: 'public/models/props/kinetic-hall/03-adjustable-low-clearance-gantry.glb',
    evidencePath,
    byteSize: 1098684,
    sha256: '11677bed7d5fe83c739b3c710520d361152f4be017a8ec06803b30ead05adf40',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The one-mesh gantry is valid at its authored clearance setting; its adjustable members are not separately addressable.',
    },
  },
  {
    index: 4,
    id: 'fiducial-inspection-placard',
    label: 'Portable Fiducial Inspection Placard',
    itemRecordId: 'td7cphsz2v0fhnh1dshm27ac0n8bdfbb',
    modelId: 'ks7epjxt1jdgm6p0wya52m1djn8bcjs0',
    finalAssetId: 'p9720hx7e7x21enaj2h9fcrtds8bc1rf',
    artifactId: 'original_glb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/04-fiducial-inspection-placard'),
    filePath: 'public/models/props/kinetic-hall/04-fiducial-inspection-placard.glb',
    evidencePath,
    byteSize: 902500,
    sha256: '363a163981009b78f7e5d02db2f932cdc7446ee03cc3c10d29d268d2ff615554',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The one-mesh placard is valid at its authored target angle; the tilt frame is not separately addressable.',
    },
  },
  {
    index: 5,
    id: 'precision-docking-target',
    label: 'Precision Docking Target Module',
    itemRecordId: 'td77mvg37pa50hk31s4va1d0f58bc1qq',
    modelId: 'ks79eqnxfcz3bj81rr00wbbh8h8bc4he',
    finalAssetId: 'p972gfys70f0r8pmmsffm20pen8bcbs0',
    artifactId:
      'asset_pack_item_glb:vd795smjezmkwzn67axep8qm7s8bcbkz:5:ks79eqnxfcz3bj81rr00wbbh8h8bc4he',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/05-precision-docking-target'),
    filePath: 'public/models/props/kinetic-hall/05-precision-docking-target.glb',
    evidencePath,
    byteSize: 774952,
    sha256: 'f7fb2af923959d14d6cb12471524bae2fc76717b737231d4b3e794e2211ac89d',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'A one-mesh rigid docking fixture is acceptable; no articulated mechanism is required.',
    },
  },
  {
    index: 6,
    id: 'rugged-instrument-case',
    label: 'Rugged Instrument Case',
    itemRecordId: 'td7djyfd0fv6mh314nfgrhavzn8bd6ra',
    modelId: 'ks71mrpd0c9pjrm499gtgnyafd8bd3vd',
    finalAssetId: 'p97eek7w3wdg6msr2a45ydn2ds8bcf24',
    artifactId: 'original_glb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/06-rugged-instrument-case'),
    filePath: 'public/models/props/kinetic-hall/06-rugged-instrument-case.glb',
    evidencePath,
    byteSize: 898108,
    sha256: 'd615292ca88eca132edd4cc3e99c91beb19988e8e47c95114e649b1af4bd3cce',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The final preserves the approved open-lid pose as a one-mesh rigid prop; lid, hinges, and latches are not separately addressable.',
    },
  },
  {
    index: 7,
    id: 'emergency-stop-pedestal',
    label: 'Portable Emergency-Stop Pedestal',
    itemRecordId: 'td7ekzc4r86wbf1jpny8dtncbs8bdfm8',
    modelId: 'ks7aabvgjb6d6t2zmct6k1zc558bc2gb',
    finalAssetId: 'p97118abhhe4jgvt764szvqnw58bc5b6',
    artifactId:
      'asset_pack_item_glb:vd795smjezmkwzn67axep8qm7s8bcbkz:7:ks7aabvgjb6d6t2zmct6k1zc558bc2gb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/07-emergency-stop-pedestal'),
    filePath: 'public/models/props/kinetic-hall/07-emergency-stop-pedestal.glb',
    evidencePath,
    byteSize: 747404,
    sha256: '5db476e58658c91e3ec7cb3bb0f17ab2a66241b899d9c8f9f8617a21eca03442',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The final model is visually valid but has one mesh; the mushroom button cannot be animated as a separate authored part.',
    },
  },
  {
    index: 8,
    id: 'traversable-training-ramp',
    label: 'Traversable Training Ramp',
    itemRecordId: 'standalone-model:ks73e2vzwkwqtqzjcp4qy4vej58bdq99',
    modelId: 'ks73e2vzwkwqtqzjcp4qy4vej58bdq99',
    finalAssetId: 'ks73e2vzwkwqtqzjcp4qy4vej58bdq99',
    artifactId: 'original_glb',
    publicUrl: mintRuntimeUrl('prop/kinetic-hall/08-traversable-training-ramp'),
    filePath: 'public/models/props/kinetic-hall/08-traversable-training-ramp.glb',
    evidencePath: 'data/mint/finals/kinetic-hall/ramp/artifact-manifest.json',
    byteSize: 985276,
    sha256: '5f37fde06d8a0a6ede009a4ac4660efe3795d9448ade3bfcaa3220d126bc2863',
    staged: true,
    extensionsUsed: [],
    extensionsRequired: [],
    usesDraco: false,
    requiresDraco: false,
    geometry: {
      nodes: 1,
      meshes: 1,
      primitives: 1,
      materials: 1,
      textures: 3,
      animations: 0,
      skins: 0,
    },
    capabilities: {
      rigidPropReady: true,
      articulatedInteractionReady: false,
      note: 'The exact standalone Mint model is a rigid continuous ramp. Its deterministic metric-normalization and placement evidence remain separately fail-closed until review.',
    },
  },
] as const satisfies readonly KineticHallPropAsset[]);

export const KINETIC_HALL_PROP_BY_ID = Object.freeze(
  Object.fromEntries(KINETIC_HALL_PROP_INVENTORY.map((asset) => [asset.id, asset])),
) as unknown as Readonly<Record<KineticHallPropId, KineticHallPropAsset>>;

export const KINETIC_HALL_PROP_DEFINITION = Object.freeze({
  roomId: 'kinetic-hall',
  assetPackId: KINETIC_HALL_PROP_PACK.assetPackId,
  name: KINETIC_HALL_PROP_PACK.name,
  itemCount: KINETIC_HALL_PROP_PACK.itemCount,
  inventory: KINETIC_HALL_PROP_INVENTORY,
  byId: KINETIC_HALL_PROP_BY_ID,
  supplementalModelIds: ['ks73e2vzwkwqtqzjcp4qy4vej58bdq99'],
}) satisfies MintPropPackDefinition;

if (
  KINETIC_HALL_PROP_INVENTORY.length !== KINETIC_HALL_PROP_PACK.itemCount + 1 ||
  KINETIC_HALL_PROP_INVENTORY.some((asset, index) => {
    return asset.index !== index || asset.id !== KINETIC_HALL_PROP_IDS[index];
  }) ||
  KINETIC_HALL_PROP_INVENTORY[KINETIC_HALL_PROP_PACK.itemCount]?.modelId !==
    KINETIC_HALL_PROP_DEFINITION.supplementalModelIds?.[0]
) {
  throw new Error(
    'Kinetic Hall prop inventory does not match its finalized Mint pack plus supplemental ramp ordering',
  );
}
