export const MINT_RUNTIME_URLS = {
  "animation/axiom-h1/idle": "https://cdn.mint.gg/glb/idle-glb-b99a5ac625b722e6.glb",
  "animation/axiom-h1/walk": "https://cdn.mint.gg/glb/casual-walk-inplace-glb-2d75b70b00ee37d5.glb",
  "component/forge-t7/00-tracked-lower-chassis": "https://cdn.mint.gg/glb/forge-t7-tracked-lower-chassis-normalized-8fa706ec403af3f9.glb",
  "component/forge-t7/01-rotating-upper-structure": "https://cdn.mint.gg/glb/forge-t7-rotating-upper-structure-normalized-d3572f98baf39ba8.glb",
  "component/forge-t7/02-main-boom": "https://cdn.mint.gg/glb/forge-t7-main-boom-recovery-normalized-e60260b302396daf.glb",
  "component/forge-t7/03-stick": "https://cdn.mint.gg/glb/forge-t7-stick-normalized-fdf6a735d69d9b0c.glb",
  "component/forge-t7/04-quick-change-gripper": "https://cdn.mint.gg/glb/forge-t7-quick-change-gripper-recovery-normalized-92a24a23b503c9b5.glb",
  "component/kestrel-d5/00-central-chassis": "https://cdn.mint.gg/glb/kestrel-d5-chassis-candidate-a-low-profile-x-fuselage-normalized-6888024f94dc5e98.glb",
  "component/kestrel-d5/01-duct-housing": "https://cdn.mint.gg/glb/kestrel-d5-rear-left-duct-housing-normalized-55c67a7b88b7967c.glb",
  "component/kestrel-d5/02-five-blade-rotor": "https://cdn.mint.gg/glb/kestrel-d5-rear-right-rotor-normalized-ab5e9d5fe7ede6ef.glb",
  "component/kestrel-d5/03-camera-gimbal": "https://cdn.mint.gg/glb/kestrel-d5-two-axis-camera-gimbal-normalized-745180808700ba0a.glb",
  "component/quadrant-q4/00-central-body": "https://cdn.mint.gg/glb/quadrant-q4-central-body-chassis-normalized-cc0b838d3f732266.glb",
  "component/quadrant-q4/01-front-left-upper-leg": "https://cdn.mint.gg/glb/quadrant-q4-front-left-upper-leg-normalized-21227a9592236de8.glb",
  "component/quadrant-q4/02-front-left-lower-leg-foot": "https://cdn.mint.gg/glb/quadrant-q4-front-left-lower-leg-and-foot-normalized-afce64727266993a.glb",
  "component/quadrant-q4/03-front-right-upper-leg": "https://cdn.mint.gg/glb/quadrant-q4-front-right-upper-leg-normalized-67c8651d5014071f.glb",
  "component/quadrant-q4/04-front-right-lower-leg-foot": "https://cdn.mint.gg/glb/quadrant-q4-front-right-lower-leg-and-foot-normalized-86a0abb7350e4b5d.glb",
  "component/quadrant-q4/05-rear-left-upper-leg": "https://cdn.mint.gg/glb/quadrant-q4-rear-left-upper-leg-normalized-264d5c31cbb42b87.glb",
  "component/quadrant-q4/06-rear-left-lower-leg-foot": "https://cdn.mint.gg/glb/quadrant-q4-rear-left-lower-leg-and-foot-normalized-df872319eefa3689.glb",
  "component/quadrant-q4/07-rear-right-upper-leg": "https://cdn.mint.gg/glb/quadrant-q4-rear-right-upper-leg-normalized-051822cd2520dc96.glb",
  "component/quadrant-q4/08-rear-right-lower-leg-foot": "https://cdn.mint.gg/glb/quadrant-q4-rear-right-lower-leg-and-foot-normalized-949dfede95d80e75.glb",
  "component/swift-w2/00-holonomic-base": "https://cdn.mint.gg/glb/swift-w2-compact-holonomic-base-recovery-normalized-58b51c06a7b55c22.glb",
  "component/swift-w2/01-telescoping-mast": "https://cdn.mint.gg/glb/swift-w2-telescoping-mast-torso-lift-column-normalized-cbbef8c04a76b0cc.glb",
  "component/swift-w2/02-torso-cargo": "https://cdn.mint.gg/glb/swift-w2-torso-cargo-recovery-normalized-ff05ee9db569f9c5.glb",
  "component/swift-w2/03-left-upper-arm": "https://cdn.mint.gg/glb/swift-w2-left-upper-arm-recovery-normalized-e2ce44402fe3dc71.glb",
  "component/swift-w2/04-left-forearm-wrist-tool": "https://cdn.mint.gg/glb/swift-w2-left-forearm-candidate-a-faithful-mirrored-compact-normalized-f33c7729d5dfe71d.glb",
  "component/swift-w2/05-right-upper-arm": "https://cdn.mint.gg/glb/swift-w2-right-upper-arm-recovery-normalized-83785fc460de0b22.glb",
  "component/swift-w2/06-right-forearm-wrist-tool": "https://cdn.mint.gg/glb/swift-w2-right-forearm-wrist-tool-recovery-normalized-64fbfe3f3c211c7f.glb",
  "freeplay/bouncy-playground-ball": "https://cdn.mint.gg/glb/bouncy-playground-ball-normalized-c3fbe5afd6b88ad1.glb",
  "freeplay/flying-disc": "https://cdn.mint.gg/glb/flying-disc-normalized-5797a58aca3d2878.glb",
  "freeplay/metal-barrel": "https://cdn.mint.gg/glb/metal-barrel-normalized-3db1e220289ccbed.glb",
  "freeplay/rugged-cargo-case": "https://cdn.mint.gg/glb/rugged-cargo-case-normalized-521ff96a8661e563.glb",
  "freeplay/traffic-cone": "https://cdn.mint.gg/glb/traffic-cone-normalized-8763f4a66568e546.glb",
  "freeplay/wooden-crate": "https://cdn.mint.gg/glb/wooden-crate-normalized-af2ab13fcc00ae51.glb",
  "prop/crisis-bay/00-portable-large-shutoff-valve-trainer": "https://cdn.mint.gg/glb/portable-large-shutoff-valve-trainer-normalized-095777f46d632d7f.glb",
  "prop/crisis-bay/01-instrumented-rescue-mannequin": "https://cdn.mint.gg/glb/instrumented-rescue-mannequin-normalized-a191ec6e43b57924.glb",
  "prop/crisis-bay/02-sealed-rescue-equipment-case": "https://cdn.mint.gg/glb/sealed-rescue-equipment-case-normalized-e389c0f4b888c95d.glb",
  "prop/crisis-bay/03-emergency-supply-tote": "https://cdn.mint.gg/glb/emergency-supply-tote-normalized-fae5a622bd5819f8.glb",
  "prop/crisis-bay/04-modular-structural-debris-block": "https://cdn.mint.gg/glb/modular-structural-debris-block-normalized-7e7496fcc74fcb87.glb",
  "prop/crisis-bay/05-disabled-equipment-recovery-bogie": "https://cdn.mint.gg/glb/disabled-equipment-recovery-bogie-normalized-28e5c64a8e61e17f.glb",
  "prop/crisis-bay/06-leak-localization-cylinder-trainer": "https://cdn.mint.gg/glb/leak-localization-cylinder-trainer-normalized-0d53839db6d305d9.glb",
  "prop/crisis-bay/07-portable-isolation-control-cabinet": "https://cdn.mint.gg/glb/portable-isolation-control-cabinet-normalized-44d7b364d20b6a63.glb",
  "prop/kinetic-hall/00-powered-sliding-obstacle-sled": "https://cdn.mint.gg/glb/powered-sliding-obstacle-sled-normalized-3544aa69cc197379.glb",
  "prop/kinetic-hall/01-modular-weighted-safety-barrier": "https://cdn.mint.gg/glb/modular-weighted-safety-barrier-normalized-3e9a42681261f75a.glb",
  "prop/kinetic-hall/02-instrumented-slalom-cone": "https://cdn.mint.gg/glb/instrumented-slalom-cone-normalized-4bdd4a50541895a3.glb",
  "prop/kinetic-hall/03-adjustable-low-clearance-gantry": "https://cdn.mint.gg/glb/adjustable-low-clearance-gantry-insert-normalized-11677bed7d5fe83c.glb",
  "prop/kinetic-hall/04-fiducial-inspection-placard": "https://cdn.mint.gg/glb/portable-fiducial-inspection-placard-normalized-363a163981009b78.glb",
  "prop/kinetic-hall/05-precision-docking-target": "https://cdn.mint.gg/glb/precision-docking-target-module-normalized-f7fb2af923959d14.glb",
  "prop/kinetic-hall/06-rugged-instrument-case": "https://cdn.mint.gg/glb/rugged-instrument-case-normalized-d615292ca88eca13.glb",
  "prop/kinetic-hall/07-emergency-stop-pedestal": "https://cdn.mint.gg/glb/portable-emergency-stop-pedestal-normalized-5db476e58658c91e.glb",
  "prop/kinetic-hall/08-traversable-training-ramp": "https://cdn.mint.gg/glb/hazard-edge-ramp-normalized-5f37fde06d8a0a6e.glb",
  "prop/precision-cell/00-stackable-parts-bin": "https://cdn.mint.gg/glb/stackable-machine-vision-parts-bin-normalized-9db9a0751f7eaf07.glb",
  "prop/precision-cell/01-collaborative-transport-tote": "https://cdn.mint.gg/glb/latching-collaborative-transport-tote-normalized-5066ec3bb1bb608f.glb",
  "prop/precision-cell/02-calibrated-insertion-component": "https://cdn.mint.gg/glb/calibrated-insertion-component-normalized-2cbc4e8d86479453.glb",
  "prop/precision-cell/03-instrumented-assembly-fixture": "https://cdn.mint.gg/glb/instrumented-assembly-fixture-normalized-1e2c0db2fb87b369.glb",
  "prop/precision-cell/04-heavy-exchange-fixture": "https://cdn.mint.gg/glb/palletized-heavy-exchange-fixture-normalized-9e70ee1493f8579d.glb",
  "prop/precision-cell/05-barcode-delivery-parcel": "https://cdn.mint.gg/glb/lightweight-barcode-delivery-parcel-normalized-132bfb276eef49d6.glb",
  "prop/precision-cell/06-optical-inspection-module": "https://cdn.mint.gg/glb/fragile-optical-inspection-module-normalized-bc75e92d64d782eb.glb",
  "prop/precision-cell/07-electric-torque-driver": "https://cdn.mint.gg/glb/robot-compatible-electric-torque-driver-normalized-cdc2f63944a6e2fb.glb",
  "robot/axiom-h1/rigged": "https://cdn.mint.gg/glb/axiom-h1-rigged-character-glb-6c05ce1e99b0621c.glb"
} as const;

export type MintRuntimeAssetKey = keyof typeof MINT_RUNTIME_URLS;

export function mintRuntimeUrl<Key extends MintRuntimeAssetKey>(
  key: Key,
): (typeof MINT_RUNTIME_URLS)[Key] {
  return MINT_RUNTIME_URLS[key];
}
